[build]
  command = "echo 'EMAIL_PUBLIC_KEY=oJLs2ZEGtvA6lc1_5' >> .env"
  command = "echo 'EMAIL_SERVICE_ID=service_np85oop' >> .env"
  command = "echo 'EMAIL_TEMPLATE_ID=template_hifrbx6' >> .env"
  command = "yarn build"